version: '3.8'

services:
  cache-redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - cache-redis-data:/data
    ports:
      - 6379:6379
  
  persistence-postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - persistence-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  persistence-postgres-data:
  cache-redis-data: